from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_end_train_dialog(object):
    def setupUi(self, end_train_dialog):
        end_train_dialog.setObjectName("end_train_dialog")
        end_train_dialog.resize(1264, 728)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(end_train_dialog.sizePolicy().hasHeightForWidth())
        end_train_dialog.setSizePolicy(sizePolicy)
        end_train_dialog.setMinimumSize(QtCore.QSize(900, 600))
        end_train_dialog.setMaximumSize(QtCore.QSize(2000, 2000))
        self.verticalLayout = QtWidgets.QVBoxLayout(end_train_dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_frame = QtWidgets.QFrame(end_train_dialog)
        self.content_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.content_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_frame = QtWidgets.QFrame(self.content_frame)
        self.text_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.text_frame)
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.train_end_text = QtWidgets.QLabel(self.text_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_end_text.sizePolicy().hasHeightForWidth())
        self.train_end_text.setSizePolicy(sizePolicy)
        self.train_end_text.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(26)
        self.train_end_text.setFont(font)
        self.train_end_text.setObjectName("train_end_text")
        self.verticalLayout_4.addWidget(self.train_end_text, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.main_frame = QtWidgets.QFrame(self.text_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_5.setContentsMargins(20, 20, -1, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.heading_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heading_frame.sizePolicy().hasHeightForWidth())
        self.heading_frame.setSizePolicy(sizePolicy)
        self.heading_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.heading_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heading_frame.setObjectName("heading_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.heading_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fails_text = QtWidgets.QLabel(self.heading_frame)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(22)
        self.fails_text.setFont(font)
        self.fails_text.setAlignment(QtCore.Qt.AlignCenter)
        self.fails_text.setObjectName("fails_text")
        self.horizontalLayout_3.addWidget(self.fails_text)
        self.res_text = QtWidgets.QLabel(self.heading_frame)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(22)
        self.res_text.setFont(font)
        self.res_text.setAlignment(QtCore.Qt.AlignCenter)
        self.res_text.setObjectName("res_text")
        self.horizontalLayout_3.addWidget(self.res_text)
        self.verticalLayout_5.addWidget(self.heading_frame)
        self.fails_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fails_frame.sizePolicy().hasHeightForWidth())
        self.fails_frame.setSizePolicy(sizePolicy)
        self.fails_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fails_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fails_frame.setObjectName("fails_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fails_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fails_table = QtWidgets.QTableWidget(self.fails_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fails_table.sizePolicy().hasHeightForWidth())
        self.fails_table.setSizePolicy(sizePolicy)
        self.fails_table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(15)
        self.fails_table.setFont(font)
        self.fails_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fails_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fails_table.setLineWidth(1)
        self.fails_table.setMidLineWidth(1)
        self.fails_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.fails_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fails_table.setDragEnabled(False)
        self.fails_table.setGridStyle(QtCore.Qt.SolidLine)
        self.fails_table.setColumnCount(3)
        self.fails_table.setObjectName("fails_table")
        self.fails_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fails_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fails_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fails_table.setHorizontalHeaderItem(2, item)
        self.fails_table.horizontalHeader().setVisible(True)
        self.fails_table.horizontalHeader().setCascadingSectionResizes(True)
        self.fails_table.horizontalHeader().setDefaultSectionSize(206)
        self.fails_table.horizontalHeader().setHighlightSections(True)
        self.fails_table.horizontalHeader().setMinimumSectionSize(0)
        self.fails_table.horizontalHeader().setSortIndicatorShown(True)
        self.fails_table.horizontalHeader().setStretchLastSection(False)
        self.fails_table.verticalHeader().setVisible(False)
        self.fails_table.verticalHeader().setCascadingSectionResizes(False)
        self.fails_table.verticalHeader().setDefaultSectionSize(29)
        self.fails_table.verticalHeader().setHighlightSections(True)
        self.fails_table.verticalHeader().setSortIndicatorShown(False)
        self.fails_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.fails_table)
        self.results_frame = QtWidgets.QFrame(self.fails_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_frame.sizePolicy().hasHeightForWidth())
        self.results_frame.setSizePolicy(sizePolicy)
        self.results_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.results_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.results_frame.setObjectName("results_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.results_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.heading_small_frame = QtWidgets.QFrame(self.results_frame)
        self.heading_small_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.heading_small_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heading_small_frame.setObjectName("heading_small_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.heading_small_frame)
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.percent_text = QtWidgets.QLabel(self.heading_small_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percent_text.sizePolicy().hasHeightForWidth())
        self.percent_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(20)
        self.percent_text.setFont(font)
        self.percent_text.setAlignment(QtCore.Qt.AlignCenter)
        self.percent_text.setObjectName("percent_text")
        self.horizontalLayout_5.addWidget(self.percent_text)
        self.verticalLayout_6.addWidget(self.heading_small_frame)
        self.diagram_frame = QtWidgets.QFrame(self.results_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diagram_frame.sizePolicy().hasHeightForWidth())
        self.diagram_frame.setSizePolicy(sizePolicy)
        self.diagram_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.diagram_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.diagram_frame.setObjectName("diagram_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.diagram_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget = QtWidgets.QWidget(self.diagram_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_7.addWidget(self.widget)
        self.verticalLayout_6.addWidget(self.diagram_frame)
        self.horizontalLayout_4.addWidget(self.results_frame)
        self.verticalLayout_5.addWidget(self.fails_frame)
        self.verticalLayout_4.addWidget(self.main_frame)
        self.verticalLayout_3.addWidget(self.text_frame)
        self.verticalLayout.addWidget(self.content_frame)
        self.bottom_frame = QtWidgets.QFrame(end_train_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_frame.sizePolicy().hasHeightForWidth())
        self.bottom_frame.setSizePolicy(sizePolicy)
        self.bottom_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bottom_frame.setStyleSheet("background-color: rgb(69, 82, 255);")
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 22)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ok_btn = QtWidgets.QPushButton(self.bottom_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_btn.sizePolicy().hasHeightForWidth())
        self.ok_btn.setSizePolicy(sizePolicy)
        self.ok_btn.setMinimumSize(QtCore.QSize(100, 20))
        self.ok_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ok_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                  "")
        self.ok_btn.setObjectName("ok_btn")
        self.verticalLayout_2.addWidget(self.ok_btn, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.bottom_frame)

        self.retranslateUi(end_train_dialog)
        QtCore.QMetaObject.connectSlotsByName(end_train_dialog)

    def retranslateUi(self, end_train_dialog):
        _translate = QtCore.QCoreApplication.translate
        end_train_dialog.setWindowTitle(_translate("end_train_dialog", "Тренировка окончена"))
        self.train_end_text.setText(_translate("end_train_dialog", "Тренировка окончена!"))
        self.fails_text.setText(_translate("end_train_dialog", "Ошибки"))
        self.res_text.setText(_translate("end_train_dialog", "Результаты:"))
        self.fails_table.setSortingEnabled(True)
        item = self.fails_table.horizontalHeaderItem(0)
        item.setText(_translate("end_train_dialog", "Вопрос"))
        item = self.fails_table.horizontalHeaderItem(1)
        item.setText(_translate("end_train_dialog", "Ваш ответ"))
        item = self.fails_table.horizontalHeaderItem(2)
        item.setText(_translate("end_train_dialog", "Правильный ответ"))
        self.percent_text.setText(_translate("end_train_dialog", "Процент"))
        self.ok_btn.setText(_translate("end_train_dialog", "ОК"))


class train_end_dialog(QtWidgets.QDialog, Ui_end_train_dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        header = self.fails_table.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
