from PyQt5 import QtCore, QtGui, QtWidgets, QtChart


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        MainWindow.setMaximumSize(QtCore.QSize(2400, 1400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 700))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbar = QtWidgets.QFrame(self.centralwidget)
        self.topbar.setMaximumSize(QtCore.QSize(10000, 40))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.topbar.setFont(font)
        self.topbar.setStyleSheet("background-color: rgb(253, 150, 59);")
        self.topbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topbar)
        self.horizontalLayout.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.topbar_left = QtWidgets.QFrame(self.topbar)
        self.topbar_left.setMinimumSize(QtCore.QSize(120, 40))
        self.topbar_left.setMaximumSize(QtCore.QSize(80, 10000))
        self.topbar_left.setStyleSheet("background-color: rgb(233, 112, 38);")
        self.topbar_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topbar_left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.topbar_left.setObjectName("topbar_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.topbar_left)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu_btn = QtWidgets.QPushButton(self.topbar_left)
        self.menu_btn.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(15)
        self.menu_btn.setFont(font)
        self.menu_btn.setStyleSheet(" QPushButton {\n"
                                    "    background-color: rgb(223, 110, 30);\n"
                                    " }\n"
                                    " QPushButton:hover {\n"
                                    "     background-color: rgb(255, 209, 9);\n"
                                    " }")
        self.menu_btn.setObjectName("menu_btn")
        self.verticalLayout_2.addWidget(self.menu_btn)
        self.horizontalLayout.addWidget(self.topbar_left, 0, QtCore.Qt.AlignLeft)
        self.topbar_right = QtWidgets.QFrame(self.topbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topbar_right.sizePolicy().hasHeightForWidth())
        self.topbar_right.setSizePolicy(sizePolicy)
        self.topbar_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar_right.setObjectName("topbar_right")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.topbar_right)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name_of_page_label = QtWidgets.QLabel(self.topbar_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_of_page_label.sizePolicy().hasHeightForWidth())
        self.name_of_page_label.setSizePolicy(sizePolicy)
        self.name_of_page_label.setMinimumSize(QtCore.QSize(0, 0))
        self.name_of_page_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.name_of_page_label.setFont(font)
        self.name_of_page_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name_of_page_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_of_page_label.setObjectName("name_of_page_label")
        self.horizontalLayout_3.addWidget(self.name_of_page_label)
        self.horizontalLayout.addWidget(self.topbar_right)
        self.verticalLayout.addWidget(self.topbar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setMinimumSize(QtCore.QSize(80, 100))
        self.content.setMaximumSize(QtCore.QSize(10000, 10000))
        self.content.setStyleSheet("background-color: rgb(254, 255, 255);")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Plain)
        self.content.setLineWidth(0)
        self.content.setMidLineWidth(0)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_line_frame = QtWidgets.QFrame(self.content)
        self.left_line_frame.setMinimumSize(QtCore.QSize(120, 0))
        self.left_line_frame.setMaximumSize(QtCore.QSize(120, 16777215))
        self.left_line_frame.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(253, 119, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.left_line_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_line_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_line_frame.setObjectName("left_line_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.left_line_frame)
        self.verticalLayout_8.setContentsMargins(10, 0, 10, 10000)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.menu_frame_2 = QtWidgets.QFrame(self.left_line_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_frame_2.sizePolicy().hasHeightForWidth())
        self.menu_frame_2.setSizePolicy(sizePolicy)
        self.menu_frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.menu_frame_2.setMaximumSize(QtCore.QSize(200, 400))
        self.menu_frame_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.menu_frame_2.setBaseSize(QtCore.QSize(0, 0))
        self.menu_frame_2.setStyleSheet("background-color: rgb(253, 150, 59);")
        self.menu_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menu_frame_2.setLineWidth(0)
        self.menu_frame_2.setObjectName("menu_frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.menu_frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.start_menu_btn = QtWidgets.QPushButton(self.menu_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_menu_btn.sizePolicy().hasHeightForWidth())
        self.start_menu_btn.setSizePolicy(sizePolicy)
        self.start_menu_btn.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(15)
        self.start_menu_btn.setFont(font)
        self.start_menu_btn.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 246, 47);\n"
                                          "    border: 0px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(250, 255, 111);\n"
                                          "}")
        self.start_menu_btn.setObjectName("start_menu_btn")
        self.verticalLayout_5.addWidget(self.start_menu_btn)
        self.train_menu_btn = QtWidgets.QPushButton(self.menu_frame_2)
        self.train_menu_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_menu_btn.sizePolicy().hasHeightForWidth())
        self.train_menu_btn.setSizePolicy(sizePolicy)
        self.train_menu_btn.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(15)
        self.train_menu_btn.setFont(font)
        self.train_menu_btn.setStyleSheet("QPushButton {\n"
                                          "    background-color: rgb(255, 246, 47);\n"
                                          "    border: 0px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(250, 255, 111);\n"
                                          "}")
        self.train_menu_btn.setObjectName("train_menu_btn")
        self.verticalLayout_5.addWidget(self.train_menu_btn)
        self.addtest_menu_btn = QtWidgets.QPushButton(self.menu_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addtest_menu_btn.sizePolicy().hasHeightForWidth())
        self.addtest_menu_btn.setSizePolicy(sizePolicy)
        self.addtest_menu_btn.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(15)
        self.addtest_menu_btn.setFont(font)
        self.addtest_menu_btn.setStyleSheet("QPushButton {\n"
                                            "    background-color: rgb(255, 246, 47);\n"
                                            "    border: 0px;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(250, 255, 111);\n"
                                            "}")
        self.addtest_menu_btn.setObjectName("addtest_menu_btn")
        self.verticalLayout_5.addWidget(self.addtest_menu_btn)
        self.verticalLayout_8.addWidget(self.menu_frame_2)
        self.horizontalLayout_2.addWidget(self.left_line_frame)
        self.main_frame = QtWidgets.QFrame(self.content)
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.start_page = QtWidgets.QWidget()
        self.start_page.setObjectName("start_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.start_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.start_page_text = QtWidgets.QTextBrowser(self.start_page)
        self.start_page_text.setMaximumSize(QtCore.QSize(16777215, 170))
        self.start_page_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.start_page_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.start_page_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.start_page_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.start_page_text.setObjectName("start_page_text")
        self.verticalLayout_3.addWidget(self.start_page_text)
        self.start_btns_frame = QtWidgets.QFrame(self.start_page)
        self.start_btns_frame.setMinimumSize(QtCore.QSize(0, 475))
        self.start_btns_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.start_btns_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_btns_frame.setLineWidth(0)
        self.start_btns_frame.setObjectName("start_btns_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.start_btns_frame)
        self.horizontalLayout_5.setContentsMargins(100, -1, 100, 0)
        self.horizontalLayout_5.setSpacing(100)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.train_btn = QtWidgets.QPushButton(self.start_btns_frame)
        self.train_btn.setMinimumSize(QtCore.QSize(0, 200))
        self.train_btn.setStyleSheet("QPushButton {\n"
                                     "    border: 0px;\n"
                                     "    image: url(:/start_page/lamp_off.png);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "    image: url(:/start_page/lamp_on.png);\n"
                                     "}")
        self.train_btn.setText("")
        self.train_btn.setObjectName("train_btn")
        self.horizontalLayout_5.addWidget(self.train_btn)
        self.verticalLayout_3.addWidget(self.start_btns_frame)
        self.stackedWidget.addWidget(self.start_page)
        self.choose_mode_page = QtWidgets.QWidget()
        self.choose_mode_page.setObjectName("choose_mode_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.choose_mode_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.choose_mode_text = QtWidgets.QTextEdit(self.choose_mode_page)
        self.choose_mode_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.choose_mode_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.choose_mode_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.choose_mode_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.choose_mode_text.setObjectName("choose_mode_text")
        self.verticalLayout_4.addWidget(self.choose_mode_text)
        self.choose_mode_frame = QtWidgets.QFrame(self.choose_mode_page)
        self.choose_mode_frame.setMinimumSize(QtCore.QSize(0, 550))
        self.choose_mode_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.choose_mode_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_mode_frame.setObjectName("choose_mode_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.choose_mode_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 100)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.custom_test_frame = QtWidgets.QFrame(self.choose_mode_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_test_frame.sizePolicy().hasHeightForWidth())
        self.custom_test_frame.setSizePolicy(sizePolicy)
        self.custom_test_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.custom_test_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.custom_test_frame.setObjectName("custom_test_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.custom_test_frame)
        self.verticalLayout_13.setContentsMargins(300, 0, 300, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.your_tests_text = QtWidgets.QLabel(self.custom_test_frame)
        self.your_tests_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(20)
        self.your_tests_text.setFont(font)
        self.your_tests_text.setAlignment(QtCore.Qt.AlignCenter)
        self.your_tests_text.setObjectName("your_tests_text")
        self.verticalLayout_13.addWidget(self.your_tests_text)
        self.custom_tests_combobox = QtWidgets.QComboBox(self.custom_test_frame)
        self.custom_tests_combobox.setMinimumSize(QtCore.QSize(400, 0))
        self.custom_tests_combobox.setMaximumSize(QtCore.QSize(1000000, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.custom_tests_combobox.setFont(font)
        self.custom_tests_combobox.setObjectName("custom_tests_combobox")
        self.verticalLayout_13.addWidget(self.custom_tests_combobox)
        self.label_2 = QtWidgets.QLabel(self.custom_test_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_13.addWidget(self.label_2)
        self.count_answers_combobox = QtWidgets.QComboBox(self.custom_test_frame)
        self.count_answers_combobox.setMinimumSize(QtCore.QSize(0, 23))
        self.count_answers_combobox.setObjectName("count_answers_combobox")
        self.count_answers_combobox.addItem("")
        self.count_answers_combobox.addItem("")
        self.verticalLayout_13.addWidget(self.count_answers_combobox)
        self.start_custom_test_btn = QtWidgets.QPushButton(self.custom_test_frame)
        self.start_custom_test_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(20)
        self.start_custom_test_btn.setFont(font)
        self.start_custom_test_btn.setStyleSheet("QPushButton {\n"
                                                 "    border: 0px;\n"
                                                 "    background-color: rgb(253, 150, 59);\n"
                                                 "\n"
                                                 "}\n"
                                                 "QPushButton:hover {\n"
                                                 "    \n"
                                                 "    background-color: rgb(245, 255, 60);\n"
                                                 "}")
        self.start_custom_test_btn.setObjectName("start_custom_test_btn")
        self.verticalLayout_13.addWidget(self.start_custom_test_btn)
        self.verticalLayout_6.addWidget(self.custom_test_frame)
        self.verticalLayout_4.addWidget(self.choose_mode_frame)
        self.stackedWidget.addWidget(self.choose_mode_page)
        self.udarenia_training_page = QtWidgets.QWidget()
        self.udarenia_training_page.setObjectName("udarenia_training_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.udarenia_training_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.top_frame = QtWidgets.QFrame(self.udarenia_training_page)
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.top_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.task_text = QtWidgets.QTextEdit(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.task_text.setFont(font)
        self.task_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.task_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.task_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.task_text.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.task_text.setTabChangesFocus(False)
        self.task_text.setReadOnly(True)
        self.task_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.task_text.setObjectName("task_text")
        self.horizontalLayout_6.addWidget(self.task_text)
        self.verticalLayout_7.addWidget(self.top_frame)
        self.right_false_frame = QtWidgets.QFrame(self.udarenia_training_page)
        self.right_false_frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.right_false_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_false_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_false_frame.setObjectName("right_false_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.right_false_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.answer_text = QtWidgets.QTextEdit(self.right_false_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_text.sizePolicy().hasHeightForWidth())
        self.answer_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.answer_text.setFont(font)
        self.answer_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.answer_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.answer_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.answer_text.setReadOnly(True)
        self.answer_text.setObjectName("answer_text")
        self.horizontalLayout_7.addWidget(self.answer_text)
        self.verticalLayout_7.addWidget(self.right_false_frame)
        self.central_frame = QtWidgets.QFrame(self.udarenia_training_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_frame.sizePolicy().hasHeightForWidth())
        self.central_frame.setSizePolicy(sizePolicy)
        self.central_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_frame.setObjectName("central_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.central_frame)
        self.gridLayout.setContentsMargins(50, 0, 50, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.right_btn = QtWidgets.QPushButton(self.central_frame)
        self.right_btn.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("PT Sans Narrow")
        font.setPointSize(20)
        self.right_btn.setFont(font)
        self.right_btn.setStyleSheet("QPushButton {\n"
                                     "    border: 0px;\n"
                                     "    background-color: rgb(253, 150, 59);\n"
                                     "\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    \n"
                                     "    background-color: rgb(245, 255, 60);\n"
                                     "}")
        self.right_btn.setObjectName("right_btn")
        self.gridLayout.addWidget(self.right_btn, 0, 1, 1, 1)
        self.left_btn = QtWidgets.QPushButton(self.central_frame)
        self.left_btn.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("PT Sans Narrow")
        font.setPointSize(20)
        self.left_btn.setFont(font)
        self.left_btn.setStyleSheet("QPushButton {\n"
                                    "    border: 0px;\n"
                                    "    background-color: rgb(253, 150, 59);\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    \n"
                                    "    background-color: rgb(245, 255, 60);\n"
                                    "}")
        self.left_btn.setObjectName("left_btn")
        self.gridLayout.addWidget(self.left_btn, 0, 0, 1, 1)
        self.left_d_btn = QtWidgets.QPushButton(self.central_frame)
        self.left_d_btn.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("PT Sans Narrow")
        font.setPointSize(20)
        self.left_d_btn.setFont(font)
        self.left_d_btn.setStyleSheet("QPushButton {\n"
                                      "    border: 0px;\n"
                                      "    background-color: rgb(253, 150, 59);\n"
                                      "\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    \n"
                                      "    background-color: rgb(245, 255, 60);\n"
                                      "}")
        self.left_d_btn.setObjectName("left_d_btn")
        self.gridLayout.addWidget(self.left_d_btn, 1, 0, 1, 1)
        self.right_d_btn = QtWidgets.QPushButton(self.central_frame)
        self.right_d_btn.setEnabled(True)
        self.right_d_btn.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("PT Sans Narrow")
        font.setPointSize(20)
        self.right_d_btn.setFont(font)
        self.right_d_btn.setStyleSheet("QPushButton {\n"
                                       "    border: 0px;\n"
                                       "    background-color: rgb(253, 150, 59);\n"
                                       "\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    \n"
                                       "    background-color: rgb(245, 255, 60);\n"
                                       "}")
        self.right_d_btn.setObjectName("right_d_btn")
        self.gridLayout.addWidget(self.right_d_btn, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.central_frame)
        self.bottom_frame = QtWidgets.QFrame(self.udarenia_training_page)
        self.bottom_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 400))
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bottom_frame)
        self.verticalLayout_9.setContentsMargins(0, 15, 0, 70)
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.next_btn = QtWidgets.QPushButton(self.bottom_frame)
        self.next_btn.setMinimumSize(QtCore.QSize(200, 75))
        self.next_btn.setMaximumSize(QtCore.QSize(1000000, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Sans Narrow")
        font.setPointSize(22)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("QPushButton {\n"
                                    "    border: 0px;\n"
                                    "    background-color: rgb(253, 150, 59);\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    \n"
                                    "    background-color: rgb(245, 255, 60);\n"
                                    "}")
        self.next_btn.setObjectName("next_btn")
        self.verticalLayout_9.addWidget(self.next_btn)
        self.end_btn = QtWidgets.QPushButton(self.bottom_frame)
        self.end_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("PT Sans Narrow")
        font.setPointSize(20)
        self.end_btn.setFont(font)
        self.end_btn.setStyleSheet("QPushButton {\n"
                                   "    border: 0px;\n"
                                   "    background-color: rgb(252, 27, 24);\n"
                                   "\n"
                                   "}\n"
                                   "QPushButton:hover {\n"
                                   "    background-color: rgb(245, 255, 60);\n"
                                   "}")
        self.end_btn.setObjectName("end_btn")
        self.verticalLayout_9.addWidget(self.end_btn)
        self.verticalLayout_7.addWidget(self.bottom_frame, 0, QtCore.Qt.AlignHCenter)
        self.bottom_udareniya_frame = QtWidgets.QFrame(self.udarenia_training_page)
        self.bottom_udareniya_frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.bottom_udareniya_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_udareniya_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_udareniya_frame.setObjectName("bottom_udareniya_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.bottom_udareniya_frame)
        self.horizontalLayout_9.setContentsMargins(10, 0, 10, 3)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.timer = QtWidgets.QTimeEdit(self.bottom_udareniya_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timer.sizePolicy().hasHeightForWidth())
        self.timer.setSizePolicy(sizePolicy)
        self.timer.setMinimumSize(QtCore.QSize(0, 30))
        self.timer.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(20)
        self.timer.setFont(font)
        self.timer.setStyleSheet("border: 0px;")
        self.timer.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.timer.setReadOnly(True)
        self.timer.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timer.setAccelerated(False)
        self.timer.setKeyboardTracking(False)
        self.timer.setObjectName("timer")
        self.horizontalLayout_9.addWidget(self.timer, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignBottom)
        self.counter = QtWidgets.QLabel(self.bottom_udareniya_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counter.sizePolicy().hasHeightForWidth())
        self.counter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(19)
        self.counter.setFont(font)
        self.counter.setObjectName("counter")
        self.horizontalLayout_9.addWidget(self.counter, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)
        self.verticalLayout_7.addWidget(self.bottom_udareniya_frame)
        self.stackedWidget.addWidget(self.udarenia_training_page)
        self.add_test_page = QtWidgets.QWidget()
        self.add_test_page.setObjectName("add_test_page")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.add_test_page)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.add_list_left_frame = QtWidgets.QFrame(self.add_test_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_list_left_frame.sizePolicy().hasHeightForWidth())
        self.add_list_left_frame.setSizePolicy(sizePolicy)
        self.add_list_left_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.add_list_left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.add_list_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_list_left_frame.setObjectName("add_list_left_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.add_list_left_frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.add_test_tablewidget = QtWidgets.QTableWidget(self.add_list_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_test_tablewidget.sizePolicy().hasHeightForWidth())
        self.add_test_tablewidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(15)
        self.add_test_tablewidget.setFont(font)
        self.add_test_tablewidget.setLineWidth(1)
        self.add_test_tablewidget.setMidLineWidth(1)
        self.add_test_tablewidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.add_test_tablewidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.add_test_tablewidget.setGridStyle(QtCore.Qt.SolidLine)
        self.add_test_tablewidget.setObjectName("add_test_tablewidget")
        self.add_test_tablewidget.setColumnCount(2)
        self.add_test_tablewidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.add_test_tablewidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        item.setFont(font)
        self.add_test_tablewidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.add_test_tablewidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        item.setFont(font)
        self.add_test_tablewidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.add_test_tablewidget.setItem(0, 1, item)
        self.add_test_tablewidget.horizontalHeader().setVisible(False)
        self.add_test_tablewidget.horizontalHeader().setCascadingSectionResizes(True)
        self.add_test_tablewidget.horizontalHeader().setDefaultSectionSize(100)
        self.add_test_tablewidget.horizontalHeader().setHighlightSections(True)
        self.add_test_tablewidget.horizontalHeader().setMinimumSectionSize(30)
        self.add_test_tablewidget.horizontalHeader().setSortIndicatorShown(False)
        self.add_test_tablewidget.horizontalHeader().setStretchLastSection(True)
        self.add_test_tablewidget.verticalHeader().setVisible(False)
        self.add_test_tablewidget.verticalHeader().setCascadingSectionResizes(False)
        self.add_test_tablewidget.verticalHeader().setMinimumSectionSize(20)
        self.add_test_tablewidget.verticalHeader().setSortIndicatorShown(False)
        self.add_test_tablewidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_11.addWidget(self.add_test_tablewidget)
        self.add_question_btn = QtWidgets.QPushButton(self.add_list_left_frame)
        self.add_question_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.add_question_btn.setFont(font)
        self.add_question_btn.setStyleSheet("QPushButton {\n"
                                            "    border: 0px;\n"
                                            "    background-color: rgb(253, 150, 59);\n"
                                            "\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    \n"
                                            "    background-color: rgb(245, 255, 60);\n"
                                            "}")
        self.add_question_btn.setObjectName("add_question_btn")
        self.verticalLayout_11.addWidget(self.add_question_btn)
        self.delete_question_btn = QtWidgets.QPushButton(self.add_list_left_frame)
        self.delete_question_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.delete_question_btn.setFont(font)
        self.delete_question_btn.setStyleSheet("QPushButton {\n"
                                               "    border: 0px;\n"
                                               "    background-color: rgb(255, 0, 0);\n"
                                               "\n"
                                               "}\n"
                                               "QPushButton:hover {\n"
                                               "    \n"
                                               "    background-color: rgb(245, 255, 60);\n"
                                               "}")
        self.delete_question_btn.setObjectName("delete_question_btn")
        self.verticalLayout_11.addWidget(self.delete_question_btn)
        self.horizontalLayout_8.addWidget(self.add_list_left_frame)
        self.add_list_right_frame = QtWidgets.QFrame(self.add_test_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_list_right_frame.sizePolicy().hasHeightForWidth())
        self.add_list_right_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(19)
        self.add_list_right_frame.setFont(font)
        self.add_list_right_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.add_list_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_list_right_frame.setObjectName("add_list_right_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.add_list_right_frame)
        self.verticalLayout_12.setContentsMargins(0, 180, 30, 180)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtWidgets.QLabel(self.add_list_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.add_list_right_frame)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_12.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem)
        self.test_name_text = QtWidgets.QLabel(self.add_list_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_name_text.sizePolicy().hasHeightForWidth())
        self.test_name_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(21)
        self.test_name_text.setFont(font)
        self.test_name_text.setAlignment(QtCore.Qt.AlignCenter)
        self.test_name_text.setObjectName("test_name_text")
        self.verticalLayout_12.addWidget(self.test_name_text)
        self.test_name_lineedit = QtWidgets.QLineEdit(self.add_list_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_name_lineedit.sizePolicy().hasHeightForWidth())
        self.test_name_lineedit.setSizePolicy(sizePolicy)
        self.test_name_lineedit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(16)
        self.test_name_lineedit.setFont(font)
        self.test_name_lineedit.setMaxLength(40)
        self.test_name_lineedit.setObjectName("test_name_lineedit")
        self.verticalLayout_12.addWidget(self.test_name_lineedit)
        self.create_test_btn = QtWidgets.QPushButton(self.add_list_right_frame)
        self.create_test_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(20)
        self.create_test_btn.setFont(font)
        self.create_test_btn.setStyleSheet("QPushButton {\n"
                                           "    border: 0px;\n"
                                           "    background-color: rgb(253, 150, 59);\n"
                                           "\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    \n"
                                           "    background-color: rgb(245, 255, 60);\n"
                                           "}")
        self.create_test_btn.setObjectName("create_test_btn")
        self.verticalLayout_12.addWidget(self.create_test_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem1)
        self.delete_test_btn = QtWidgets.QPushButton(self.add_list_right_frame)
        self.delete_test_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(20)
        self.delete_test_btn.setFont(font)
        self.delete_test_btn.setStyleSheet("QPushButton {\n"
                                           "    border: 0px;\n"
                                           "    background-color: rgb(255, 0, 0);\n"
                                           "\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    \n"
                                           "    background-color: rgb(245, 255, 60);\n"
                                           "}")
        self.delete_test_btn.setObjectName("delete_test_btn")
        self.verticalLayout_12.addWidget(self.delete_test_btn)
        self.horizontalLayout_8.addWidget(self.add_list_right_frame)
        self.stackedWidget.addWidget(self.add_test_page)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_test_tablewidget.verticalHeader().setVisible(True)
        self.add_test_tablewidget.horizontalHeader().setVisible(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ultest"))
        self.menu_btn.setText(_translate("MainWindow", "Меню"))
        self.name_of_page_label.setText(_translate("MainWindow", "Начальный экран   "))
        self.start_menu_btn.setText(_translate("MainWindow", "Начальная\n"
                                                             "страница🔄"))
        self.train_menu_btn.setText(_translate("MainWindow", "Тренировка\n"
                                                             "🏋"))
        self.addtest_menu_btn.setText(_translate("MainWindow", "Добавить\n"
                                                               " или изменить\n"
                                                               "тест‍💻 "))
        self.start_page_text.setHtml(_translate("MainWindow",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                                "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Добро пожаловать в ULTests!</span></p>\n"
                                                "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Это приложение поможет вам закрепить знания с помощью тестов.</span></p>\n"
                                                "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Для создания своего первого теста используйте кнопку &quot;Добавить тест&quot; в левом верхнем меню.</span></p>\n"
                                                "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Приятного пользования!</span></p></body></html>"))
        self.choose_mode_text.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                 "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                 "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Добро пожаловать в режим тренировки!</span></p>\n"
                                                 "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Здесь вы сможете подготовиться к тесту, решая бесконечно повторяющиеся задания.</span></p>\n"
                                                 "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Чтобы начать тренировку, выберите тему.</span></p></body></html>"))
        self.your_tests_text.setText(_translate("MainWindow", "Ваши тесты"))
        self.label_2.setText(_translate("MainWindow", "Количество вариантов ответов"))
        self.count_answers_combobox.setItemText(0, _translate("MainWindow", "2"))
        self.count_answers_combobox.setItemText(1, _translate("MainWindow", "4"))
        self.start_custom_test_btn.setText(_translate("MainWindow", "Начать"))
        self.task_text.setHtml(_translate("MainWindow",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'PT Sans\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                          "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\';\"><br /></p>\n"
                                          "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:24pt;\">Выберите правильное ударениеfdnsfhjldshlfdsjlkfds;fdsjfdsjfsdlfjldsjfldfjlsdjfjdsfjdsjklfdsklfjsdkfjldsjfjdslfjdsljfkdsfksdjflsfdfdsfdsf</span></p></body></html>"))
        self.answer_text.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'PT Sans\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\';\"><br /></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\';\"><br /></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\';\"><br /></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:36pt; color:#25ff06;\">Верно!</span></p></body></html>"))
        self.right_btn.setText(_translate("MainWindow", "PushButton"))
        self.left_btn.setText(_translate("MainWindow", "name"))
        self.left_d_btn.setText(_translate("MainWindow", "PushButton"))
        self.right_d_btn.setText(_translate("MainWindow", "PushButton"))
        self.next_btn.setText(_translate("MainWindow", "Следующее"))
        self.end_btn.setText(_translate("MainWindow", "Закончить"))
        self.timer.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.counter.setText(_translate("MainWindow", "name"))
        self.add_test_tablewidget.setSortingEnabled(False)
        item = self.add_test_tablewidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.add_test_tablewidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Вопрос"))
        item = self.add_test_tablewidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Правильный ответ"))
        __sortingEnabled = self.add_test_tablewidget.isSortingEnabled()
        self.add_test_tablewidget.setSortingEnabled(False)
        self.add_test_tablewidget.setSortingEnabled(__sortingEnabled)
        self.add_question_btn.setText(_translate("MainWindow", "Добавить строку для вопроса"))
        self.delete_question_btn.setText(_translate("MainWindow", "Удалить строку"))
        self.label.setText(_translate("MainWindow", "Выберите существующий тест для редактирования\n"
                                                    "или создайте новый"))
        self.test_name_text.setText(_translate("MainWindow", "Название теста"))
        self.create_test_btn.setText(_translate("MainWindow", "Создать тест"))
        self.delete_test_btn.setText(_translate("MainWindow", "Удалить тест"))

        self.add_test_tablewidget.verticalHeader().setVisible(True)
        self.add_test_tablewidget.horizontalHeader().setVisible(True)
